// Re-export the shared database client and all typed helpers
// so app code imports from a single internal alias: @/lib/db
export {
  prisma,
  // users
  getUserById,
  getUserByEmail,
  createUser,
  updateUser,
  // workspaces
  getWorkspaceById,
  getWorkspaceBySlug,
  createWorkspace,
  updateWorkspace,
  deleteWorkspace,
  getWorkspaceMembers,
  getWorkspaceMember,
  addWorkspaceMember,
  removeWorkspaceMember,
  getUserWorkspaces,
  // twins
  createTwin,
  getTwinById,
  getTwinWithLatestVersion,
  listTwins,
  updateTwin,
  deleteTwin,
  // model versions
  createModelVersion,
  getModelVersionById,
  getLatestModelVersion,
  listModelVersions,
  updateModelVersion,
  markModelVersionReady,
  markModelVersionFailed,
  // files
  createTwinFile,
  getTwinFiles,
  getTwinFileByS3Key,
  // property cache
  upsertPropertyCache,
  getElementProperties,
  queryElementsByClass,
  bulkUpsertPropertyCache,
  // issues
  createIssue,
  getIssueById,
  listIssues,
  updateIssue,
  deleteIssue,
  createIssueComment,
  getIssueComments,
  // sensors
  createSensor,
  getSensorById,
  listSensors,
  getSensorByMqttTopic,
  updateSensor,
  deleteSensor,
  recordSensorReading,
  getLatestSensorReading,
  getSensorReadings,
  // viewpoints
  createViewpoint,
  getViewpointById,
  listViewpoints,
  getIssueViewpoints,
  updateViewpoint,
  deleteViewpoint,
  // jobs
  createJob,
  getJobById,
  claimNextJob,
  markJobDone,
  markJobFailed,
  cancelJob,
  getJobsForTwin,
} from "@aec-twin/database";

export type {
  User,
  Workspace,
  WorkspaceMember,
  DigitalTwin,
  TwinModelVersion,
  TwinFile,
  ElementPropertyCache,
  Sensor,
  SensorReading,
  Issue,
  IssueComment,
  Viewpoint,
  BackgroundJob,
  WorkspaceRole,
  TwinStatus,
  ModelVersionStatus,
  IssueStatus,
  IssuePriority,
  SensorStatus,
  JobType,
  JobStatus,
} from "@aec-twin/database";
